services:
  freeswitch:
    # image: safarov/freeswitch
    # build: ./freeswitch
    image: webitel/freeswitch
    # image: mmtnrw/freeswitch
    environment:
      - SOUND_RATES=8000:16000
      - SOUND_TYPES=music:en-us-callie
      - EPMD=true
      - DUMPCAP=true
    # volumes:
      # - /Users/lya/Desktop/work/files/freeswitch/freeswitch-sounds:/usr/share/freeswitch/sounds
      # - /Users/lya/Desktop/work/files/freeswitch/freeswitch/:/etc/freeswitch
      # - /Users/lya/Desktop/work/aly_service/freeswitch/conf:/usr/local/freeswitch/conf
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5080:5080/tcp"
      - "5080:5080/udp"
      - "8021:8021/tcp"
      # - "60535-65535:60535-65535/udp"
      - "5066:5066"
      - "8443:7443"
    container_name: aly-freeswitch
    networks:
      - aly_freeswitch

networks:
  aly_freeswitch:
    driver: bridge
