services:
  mongodb:
    build: ./mongodb
    container_name: aly-mongo
    # restart: always
    volumes:
      - /Users/lya/Desktop/work/db_data/mongo_dk_db:/data/db
    ports:
      - '27017:27017'
    logging:
      driver: 'none'
    networks:
      - aly_service

  redis:
    image: redis
    container_name: aly-redis
    volumes:
      #- ./datadir:/data
      - /Users/lya/Desktop/work/aly_service/redis/redis.conf:/usr/local/etc/redis/redis.conf
      # - /Users/lya/Desktop/work/logs/redis:/logs
    command:
      - /bin/bash
      - -c
      - |
        mkdir -p /logs
        chmod -R 777 /logs
        redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - aly_service

  db:
    image: mariadb
    container_name: aly-dev189-db
    # restart: always
    ports:
      - 3306:3306
    volumes:
      - /Users/lya/Desktop/work/db_data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - aly_service

  php-fpm:
    #build: ./php-fpm
    image: liao1a/php-fpm:7.3
    container_name: aly-dev189-php-fpm
    volumes:
      # - ./php-fpm/php-dev.ini:/usr/local/etc/php/php.ini-development
      # - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /Users/lya/Desktop/work/dev189:/usr/share/nginx/html
    networks:
      - aly_service

  nginx:
    build: ./nginx
    container_name: aly-dev189-nginx
    volumes:
      - ./nginx/nginx-dev189.conf:/etc/nginx/nginx.conf
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
      - /Users/lya/Desktop/work/dev189:/usr/share/nginx/html
      # - /Users/lya/Desktop/work/logs/nginx:/var/log/nginx
    links:
      - php-fpm
    ports:
      - 8088:80
      - 8044:443
    networks:
      - aly_service
  
  nginx-default:
    build: ./nginx
    container_name: aly-nginx-default
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/lya/Desktop/work/html:/usr/share/nginx/html
    # links:
    #   - php-fpm
    ports:
      - 8089:80
    networks:
      - aly_service

  adminer:
    image: adminer
    container_name: aly-dev189-adminer
    restart: always
    ports:
      - 8099:8080
    networks:
      - aly_service

networks:
  aly_service:
    driver: bridge
