version: "3"

# docker-compose -p redis-cluster -f docker-compose.redis.cluster.yml up -d
services:
  node1:
    image: redis
    container_name: redis-1
    ports:
      - 6381:6381
      - 16381:16381
    volumes:
      - /Users/lya/work/aly_service/redis-cluster/redis-1/redis.conf:/etc/redis.conf
      - /Users/lya/work/aly_service/redis-cluster/redis-1/data:/data
    command: 
      - /bin/bash
      - -c
      - |
        mkdir -p /logs
        chmod -R 777 /logs
        redis-server /etc/redis.conf
    # restart: always

  node2:
    image: redis
    container_name: redis-2
    ports:
      - "6382:6382"
      - 16382:16382
    volumes:
      - "/Users/lya/work/aly_service/redis-cluster/redis-2/redis.conf:/etc/redis.conf"
      - "/Users/lya/work/aly_service/redis-cluster/redis-2/data:/data"
    command: 
      - /bin/bash
      - -c
      - |
        mkdir -p /logs
        chmod -R 777 /logs
        redis-server /etc/redis.conf
    # restart: always

  node3:
    image: redis
    container_name: redis-3
    ports:
      - "6383:6383"
      - 16383:16383
    volumes:
      - "/Users/lya/work/aly_service/redis-cluster/redis-3/redis.conf:/etc/redis.conf"
      - "/Users/lya/work/aly_service/redis-cluster/redis-3/data:/data"
    command: 
      - /bin/bash
      - -c
      - |
        mkdir -p /logs
        chmod -R 777 /logs
        redis-server /etc/redis.conf
    # restart: always

  node4:
    image: redis
    container_name: redis-4
    ports:
      - "6384:6384"
      - 16384:16384
    volumes:
      - "/Users/lya/work/aly_service/redis-cluster/redis-4/redis.conf:/etc/redis.conf"
      - "/Users/lya/work/aly_service/redis-cluster/redis-4/data:/data"
    command: 
      - /bin/bash
      - -c
      - |
        mkdir -p /logs
        chmod -R 777 /logs
        redis-server /etc/redis.conf
    # restart: always

  node5:
    image: redis
    container_name: redis-5
    ports:
      - "6385:6385"
      - 16385:16385
    volumes:
      - "/Users/lya/work/aly_service/redis-cluster/redis-5/redis.conf:/etc/redis.conf"
      - "/Users/lya/work/aly_service/redis-cluster/redis-5/data:/data"
    command: 
      - /bin/bash
      - -c
      - |
        mkdir -p /logs
        chmod -R 777 /logs
        redis-server /etc/redis.conf
    # restart: always

  node6:
    image: redis
    container_name: redis-6
    ports:
      - "6386:6386"
      - 16386:16386
    volumes:
      - "/Users/lya/work/aly_service/redis-cluster/redis-6/redis.conf:/etc/redis.conf"
      - "/Users/lya/work/aly_service/redis-cluster/redis-6/data:/data"
    command: 
      - /bin/bash
      - -c
      - |
        mkdir -p /logs
        chmod -R 777 /logs
        redis-server /etc/redis.conf
    # restart: always
