FROM mongo:latest

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN apt-get update

RUN apt-get -y install gettext-base

# 复制集配置文件
ADD ./init_replicate.js.template /home/init_replicate.js.template
ADD ./init_replicate.sh /home/init_replicate.sh

CMD ["mongod"]
